name = "Subset_minimal_search"
uuid = "617967a3-e185-4e1a-ad46-feef785cd8a4"
authors = ["Sofia Poludina <poludsof@fel.cvut.cz>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticBitSets = "72d6c30d-a10b-4e7e-bc09-3079d9530bdf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[extensions]
CUDAExt = "CUDA"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
CUDA = "5.6.0"
CairoMakie = "0.12.16"
DataFrames = "1.7.0"
DataStructures = "0.18.20"
Distributions = "0.25.117"
MLUtils = "0.4.4"
Makie = "0.21.16"
Optimisers = "0.3.4"
PrettyTables = "2.4.0"
ProfileCanvas = "0.1.6"
Revise = "3.7.3"
Serialization = "1.11.0"
StatsBase = "0.34.4"
Test = "1.11.0"
cuDNN = "1.4.1"
